app/models/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.String, unique=True)
    name = db.Column(db.String)
    username = db.Column(db.String)
    password = db.Column(db.String)
    contact = db.Column(db.String)
    role = db.Column(db.String)

    def is_admin(self):
        if self.role == 'admin':
            return True
        return False

app/forms/add_user.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SelectField
from wtforms.validators import DataRequired, Length


class AddUserForm(FlaskForm):
    name = StringField('Name',
                       validators=[DataRequired(), Length(3, 20)],
                       render_kw={'class': 'form-control shadow-none', 'placeholder': 'Name'})

    username = StringField('Username',
                           validators=[DataRequired()],
                           render_kw={'class': 'form-control shadow-none', 'placeholder': 'Username'})

    password = PasswordField('Password',
                             validators=[DataRequired()],
                             render_kw={'class': 'form-control shadow-none', 'placeholder': 'Password'})

    role = SelectField('Role', choices=[('student', 'Student'), ('employer', 'Employer'), ('admin', 'Admin')], render_kw={'class': 'form-select shadow-none'})

    contact = StringField('Contact',
                          validators=[DataRequired()],
                          render_kw={'class': 'form-control shadow-none', 'placeholder': 'Contact'})

app/forms/edit.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SelectField
from wtforms.validators import DataRequired, Length


class EditForm(FlaskForm):
    name = StringField('Name',
                       validators=[DataRequired(), Length(3, 20)],
                       render_kw={'class': 'form-control shadow-none', 'placeholder': 'Name'})

    username = StringField('Username',
                           validators=[DataRequired()],
                           render_kw={'class': 'form-control shadow-none', 'placeholder': 'Username'})

    password = PasswordField('Password',
                             render_kw={'class': 'form-control shadow-none', 'placeholder': 'Password'})

    role = SelectField('Role', choices=[('student', 'Student'), ('employer', 'Employer'), ('admin', 'Admin')],
                       render_kw={'class': 'form-select shadow-none'})

    contact = StringField('Contact',
                          validators=[DataRequired()],
                          render_kw={'class': 'form-control shadow-none', 'placeholder': 'Contact'})

app/forms/login.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('username',
                           validators=[DataRequired()],
                           render_kw={'class': 'form-control shadow-none', 'placeholder': 'Username'})

    password = PasswordField('password',
                             validators=[DataRequired()],
                             render_kw={'class': 'form-control shadow-none', 'placeholder': 'Password'})

app/__init__.py
from flask import Flask

app = Flask(__name__)
app.config.from_pyfile('config.py')

from app.models.models import db, User
db.init_app(app)

with app.app_context():
    db.create_all()


from app.views.base import base_bp
from app.views.auth import auth_bp
app.register_blueprint(base_bp)
app.register_blueprint(auth_bp)


from app.utils.bcrypt import bcrypt
bcrypt.init_app(app)

from app.utils.sessions import sessions
sessions.init_app(app)

from app.utils.admin import admin
from flask_admin.contrib.sqla import ModelView
admin.init_app(app)
admin.add_view(ModelView(User, db.session))

from app.utils.migrate import migrate
migrate.init_app(app, db)

app/views/auth.py
from flask import Blueprint, session, redirect, url_for, render_template, flash
from app.helpers.login import admin_required

from app.models.models import db, User

from app.forms.edit import EditForm
from app.forms.add_user import AddUserForm

from app.utils.bcrypt import bcrypt

from secrets import token_urlsafe

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/edit-user/<string:user_id>', methods=['GET', 'POST'])
@admin_required
def edit_user(user_id):
    user = User.query.filter_by(user_id=user_id).first()
    form = EditForm(obj=user)
    if form.validate_on_submit():
        name = form.name.data
        username = form.username.data
        password = form.password.data
        role = form.role.data
        contact = form.contact.data

        user.name = name
        user.username = username

        if password.strip() is not '':
            user.password = bcrypt.generate_password_hash(f'{password}')

        user.role = role
        user.contact = contact

        db.session.commit()

        flash('Your data has been successfully saved')
        return redirect(url_for('auth.edit_user', user_id=user.user_id))

    return render_template('edit.html', form=form, user=user)


@auth_bp.route('/delete-user/<string:user_id>', methods=['GET'])
@admin_required
def delete_user(user_id):
    user = User.query.filter_by(user_id=user_id).first()
    if user:
        db.session.delete(user)
        db.session.commit()

    return redirect(url_for('base.main'))


@auth_bp.route('/add-user', methods=['GET', 'POST'])
@admin_required
def add_user():
    form = AddUserForm()
    if form.validate_on_submit():
        user_id = token_urlsafe(16)
        name = form.name.data
        username = form.username.data
        password = form.password.data
        role = form.role.data
        contact = form.contact.data

        new_user = User(
            user_id=user_id,
            name=name,
            username=username,
            password=bcrypt.generate_password_hash(f'{password}'),
            contact=contact,
            role=role)

        db.session.add(new_user)
        db.session.commit()

        flash('New User Successfully Created')
        return redirect(url_for('auth.add_user'))
    return render_template('add.html', form=form)


@auth_bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('base.login'))

app/views/base.py
from flask import Blueprint, render_template, session, redirect, url_for, flash, request, current_app

from app.forms.login import LoginForm
from app.helpers.login import login_required
from app.models.models import User
from app.utils.bcrypt import bcrypt

base_bp = Blueprint('base', __name__)


@base_bp.route('/')
@login_required
def main():

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['USERS_PER_PAGE']

    user = User.query.filter_by(user_id=session['user_id']).first()
    users = User.query.filter(User.role != 'admin')

    users_pag = users.paginate(page=page, per_page=per_page)

    users_length = len(users.all())

    return render_template('main.html', users=users_pag, user=user, users_length=users_length)


@base_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        user = User.query.filter_by(username=username).first()
        if user:
            if bcrypt.check_password_hash(user.password, password):
                session['user_id'] = user.user_id
                return redirect(url_for('base.main'))

        flash('The username or password is incorrect')

    return render_template('login.html', form=form)


@base_bp.route('/search', methods=['GET'])
def search():
    query = request.args.get('query', 1, type=str)

    user = User.query.filter_by(user_id=session['user_id']).first()

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['USERS_PER_PAGE']

    results = User.query.filter(
        User.name.ilike(f'%{query}%') | User.role.ilike(f'%{query}%') | User.contact.ilike(f'%{query}%')).filter(User.role != 'admin')
    users_pag = results.paginate(page=page, per_page=per_page)

    result_length = len(users_pag.items)

    return render_template('main.html', users=users_pag, user=user, query=query, result_length=result_length)

app/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add User</title>
    {% include 'connectors/assets.html' %}
    

</head>
<body>

    <div class="container d-flex justify-content-start mt-2">
        <a class="btn btn-primary shadow-none" href="{{ url_for('base.main') }}"><</a>
    </div>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="container d-flex justify-content-center text-center mt-1">
                <div class="w-25 border rounded shadow p-1 mb-2 bg-success text-light">
                {% for message in messages %}
                    <span>{{ message }}</span>
                {% endfor %}
                </div>
            </div>
        {% endif %}
    {% endwith %}

    <div class="container d-flex justify-content-center mt-3">
        <form action="{{ url_for('auth.add_user') }}" class="w-25 border rounded shadow p-3" method="POST">

            {{ form.csrf_token }}
            <div class="mb-3">
                {{ form.name.label(class='form-label') }}
                {{ form.name }}
            </div>

            <div class="mb-3">
                {{ form.username.label(class='form-label') }}
                {{ form.username }}
            </div>

            <div class="mb-3">
                {{ form.password.label(class='form-label') }}
                {{ form.password }}
            </div>

            <div class="mb-3">
                {{ form.role.label(class='form-label') }}
                {{ form.role }}
            </div>

            <div class="mb-3">
                {{ form.contact.label(class='form-label') }}
                {{ form.contact }}
            </div>

            <div class="mb-2">
                <button class="btn btn-primary w-100">Save</button>
            </div>


        
        </form>
    </div>

    
    
</body>
</html>

app/templates/base/header.html
    <nav class="navbar navbar-expand-lg fs-5 navbar-dark bg-black">
      <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('base.main') }}">Main</a>
            </li>
            {% if user.is_admin() %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.add_user') }}">Add New User</a>
            </li>
            {% endif %}
          </ul>
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

app/templates/connectors/assets.html
	<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
	<script src="https://kit.fontawesome.com/0028564408.js" crossorigin="anonymous"></script>

app/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit User</title>
    {% include 'connectors/assets.html' %}
    

</head>
<body>

    <div class="container d-flex justify-content-start mt-2">
        <a class="btn btn-primary shadow-none" href="{{ url_for('base.main') }}"><</a>
    </div>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="container d-flex justify-content-center text-center mt-1">
                <div class="w-25 border rounded shadow p-1 mb-2 bg-success text-light">
                {% for message in messages %}
                    <span>{{ message }}</span>
                {% endfor %}
                </div>
            </div>
        {% endif %}
    {% endwith %}

    <div class="container d-flex justify-content-center mt-3">
        <form action="{{ url_for('auth.edit_user', user_id=user.user_id) }}" class="w-25 border rounded shadow p-3" method="POST">

            {{ form.csrf_token }}
            <div class="mb-3">
                {{ form.name.label(class='form-label') }}
                {{ form.name }}
            </div>

            <div class="mb-3">
                {{ form.username.label(class='form-label') }}
                {{ form.username }}
            </div>

            <div class="mb-3">
                {{ form.password.label(class='form-label') }}
                {{ form.password }}
            </div>

            <div class="mb-3">
                {{ form.role.label(class='form-label') }}
                {{ form.role }}
            </div>

            <div class="mb-3">
                {{ form.contact.label(class='form-label') }}
                {{ form.contact }}
            </div>

            <div class="mb-2">
                <button class="btn btn-primary w-100">Save</button>
            </div>


        
        </form>
    </div>

    
    
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% include 'connectors/assets.html' %}
    

</head>
<body>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="container d-flex justify-content-center text-center mt-1">
                <div class="w-25 border rounded shadow p-1 mb-2 bg-danger text-light">
                {% for message in messages %}
                    <span>{{ message }}</span>
                {% endfor %}
                </div>
            </div>
        {% endif %}
    {% endwith %}

    <div class="container d-flex justify-content-center mt-3">
        <form action="{{ url_for('base.login') }}" class="w-25 border rounded shadow p-3" method="POST">

            {{ form.csrf_token }}
            <div class="mb-2">
                {{ form.username }}
            </div>

            <div class="mb-2">
                {{ form.password }}
            </div>

            <div class="mb-2">
                <button class="btn btn-primary w-100">Login</button>
            </div>


        
        </form>
    </div>

    
    
</body>
</html>

app/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main</title>
    {% include 'connectors/assets.html' %}
    

</head>
<body>

    {% include 'base/header.html' %}

    <div class="table-responsive container mt-5">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Role</th>
            <th>Contact</th>
            {% if user.is_admin() %}
            <th>Operations</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
        {% for user_ in users %}
          <tr>
            <th>{{ user_.name }}</th>
            <th>{{ user_.role }}</th>
            <th>{{ user_.contact }}</th>
            {% if user.is_admin() %}
            <th class="btn-group text-center w-100" role="group">
                <a href="{{url_for('auth.edit_user', user_id=user_.user_id) }}" class="btn btn-warning"><i class="fa-solid fa-pen-to-square"></i></a>
                <a href="{{url_for('auth.delete_user', user_id=user_.user_id) }}" class="btn btn-danger"><i class="fa-solid fa-trash"></i></a>
            </th>
            {% endif %}
          </tr>
        {% endfor %}
        </tbody>
      </table>

      {% if query %}
      {% if result_length <= 0 %}
      <div class="text-center mb-5">
          <span class="text-danger font-weight-bold fs-4">Nothing was found for your query</span>
      </div>
      {% endif %}
      {% else %}
      {% if users_length <= 0 %}
      <div class="text-center">
          <span class="text-danger font-weight-bold fs-4">There aren't any users in the database</span>
      </div>
      {% endif %}
      {% endif %}


    </div>

      {% if users.pages > 1 %}
     <nav aria-label="Page navigation">
          <ul class="pagination d-flex justify-content-center">
              {% if users.has_prev %}
              
              {% if query %}
              <li class="page-item"><a class="page-link" href="?page={{ users.prev_num }}&query={{query}}">Previous</a></li>
              {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ users.prev_num }}">Previous</a></li>
              {% endif %}
              
              {% else %}
              <li class="page-item disabled"><span class="page-link">Previous</span></li>
              {% endif %}
              
              {% for page_num in users.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
              {% if page_num %}
              {% if users.page == page_num %}
              <li class="page-item active"><span class="page-link">{{ page_num }}</span></li>
              {% else %}

              {% if query %}
              <li class="page-item"><a class="page-link" href="?page={{ page_num }}&query={{query}}">{{ page_num }}</a></li>
              {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
              {% endif %}
              
              {% endif %}
              {% else %}
              <li class="page-item disabled"><span class="page-link">...</span></li>
              {% endif %}
              {% endfor %}
              {% if users.has_next %}
              
              {% if query %}
              <li class="page-item"><a class="page-link" href="?page={{ users.next_num }}&query={{query}}">Next</a></li>
              {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ users.next_num }}">Next</a></li>
              {% endif %}

              {% else %}
              <li class="page-item disabled"><span class="page-link">Next</span></li>
              {% endif %}
          </ul>
      </nav>
      {% endif %}

      <div class="container d-flex justify-content-center">
        <form action="{{ url_for('base.search') }}" class="w-25" method="GET">
          <div class="input-group">
              <input type="text" class="form-control shadow-none" placeholder="Query" value="{{query}}" name="query">
              <button class="btn btn-primary">Find</button>
            </div>
        </form>
      </div>

</body>
</html>